create table country (id int8 not null, language varchar(255), name varchar(255), primary key (id));
create table league (id int8 not null, name varchar(255), country_id int8, primary key (id));
create table player (id int8 generated by default as identity, name varchar(255), number int4, position_id int8, team_id int8, primary key (id));
create table position (id int8 not null, name varchar(255), type varchar(255), primary key (id));
create table team (id int8 not null, name varchar(255), league_id int8, primary key (id));
alter table if exists league add constraint FKtdt2rqg50rlqti7yubvppq25e foreign key (country_id) references country;
alter table if exists player add constraint FK7nbmhpuwdf14i4gydaijs9wkl foreign key (position_id) references position;
alter table if exists player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team;
alter table if exists team add constraint FK9rk8716asfr76xkn99aa3uvp foreign key (league_id) references league;
